alter table public.personas
add column if not exists usuario_sistema text,
add column if not exists rol text,
add column if not exists estado text,
add column if not exists grado text,
add column if not exists custodio_vehiculo text,
add column if not exists licencia_tipo_a text,
add column if not exists licencia_tipo_a1 text,
add column if not exists licencia_tipo_b text,
add column if not exists licencia_tipo_c text,
add column if not exists licencia_tipo_c1 text,
add column if not exists licencia_tipo_d text,
add column if not exists licencia_tipo_d1 text,
add column if not exists licencia_tipo_e text,
add column if not exists licencia_tipo_e1 text,
add column if not exists licencia_tipo_f text,
add column if not exists licencia_tipo_g text,
add column if not exists fecha_ingreso text,
add column if not exists fecha_nacimiento text,
add column if not exists genero text,
add column if not exists tipo_sangre text,
add column if not exists numero_celular text,
add column if not exists correo_electronico text,
add column if not exists direccion_domiciliaria text,
add column if not exists observacion text,
add column if not exists ausentismo_por text,
add column if not exists ausentismo_desde text,
add column if not exists ausentismo_hasta text,
add column if not exists nota_ausentismo text,
add column if not exists fecha_asignacion text,
add column if not exists asignacion_nomina text,
add column if not exists funcion_nomina text,
add column if not exists horario_nomina text,
add column if not exists lugar_formacion text,
add column if not exists consignas text,
add column if not exists base_legal text,
add column if not exists encargado_jefe_inmediato text,
add column if not exists codigo_standby text,
add column if not exists parroquia_residencia text,
add column if not exists sector_residencia text,
add column if not exists criterio_observacion text,
add column if not exists puede_ser_jp text,
add column if not exists puede_ser_auxiliar text,
add column if not exists puede_ser_cp text,
add column if not exists puede_conducir_camioneta text,
add column if not exists puede_conducir_moto text,
add column if not exists tipo_licencia text,
add column if not exists fecha_vencimiento_licencia text,
add column if not exists licencia_vigente text,
add column if not exists observacion_operativa text;

create index if not exists idx_personas_grupo
on public.personas (grupo);

create index if not exists idx_personas_estado
on public.personas (estado);